#!/usr/bin/env bash

if
  [[ -s "/Users/peterroome/Sites/dj-shop/~/Users/peterroome/.rvm/gems/ruby-2.6.3/environment" ]]
then
  source "/Users/peterroome/Sites/dj-shop/~/Users/peterroome/.rvm/gems/ruby-2.6.3/environment"
  exec bundler "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/peterroome/Sites/dj-shop/~/Users/peterroome/.rvm/gems/ruby-2.6.3/environment'" >&2
  exit 1
fi
